##@Info: Lower velocity and acceleration limits may result in trajectories that are longer in duration
##	 but may be easier to achieve for your controllers, more stable, and less dangerous.

joint_limits:
  arm_1_joint:
    has_position_limits: true
    min_position: -6.1831853
    max_position: 6.1831853
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.8
    angle_wraparound: false
  arm_2_joint:
    has_position_limits: true
    min_position: -1.9943951
    max_position: 1.9943951
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.8
    angle_wraparound: false
  arm_3_joint:
    has_position_limits: true
    min_position: -6.1831853
    max_position: 6.1831853
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.8
    angle_wraparound: false
  arm_4_joint:
    has_position_limits: true
    min_position: -1.9943951
    max_position: 1.9943951
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.8
    angle_wraparound: false
  arm_5_joint:
    has_position_limits: true
    min_position: -6.1831853
    max_position: 6.1831853
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.8
    angle_wraparound: false
  arm_6_joint:
    has_position_limits: true
    min_position: -1.9943951
    max_position: 1.9943951
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.8
    angle_wraparound: false
  arm_7_joint:
    has_position_limits: true
    min_position: -6.1831853
    max_position: 6.1831853
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.8
    angle_wraparound: false
