#Points closer than this from the sensor frame are discarded
min_sensor_dist: .15
#The default padding to associate with links if none is specified in the link description 
self_see_default_padding: .01
#The default scale to associate with links if none is specified in the link description 
self_see_default_scale: 1.0
self_see_links:
  - name: base_link
    padding: .185
    #scale: 1.0 -- optional
  - name: arm_0_link
    padding: .125
  - name: arm_1_link
    padding: .125
  - name: arm_2_link
    padding: .125
  - name: arm_3_link
    padding: .125
  - name: arm_4_link
    padding: .125
  - name: arm_5_link
    padding: .125
  - name: arm_6_link
    padding: .125
  - name: arm_7_link
    padding: .125
  - name: sdh_tip_link
    padding: .03
  - name: sdh_grasp_link
    padding: .03
  - name: sdh_palm_link
    padding: .10
  - name: sdh_finger_11_link
    padding: .06
  - name: sdh_finger_12_link
    padding: .06
  - name: sdh_finger_13_link
    padding: .06
  - name: sdh_finger_21_link
    padding: .06
  - name: sdh_finger_22_link
    padding: .06
  - name: sdh_finger_23_link
    padding: .06
  - name: sdh_thumb_1_link
    padding: .06
  - name: sdh_thumb_2_link
    padding: .06
  - name: sdh_thumb_3_link
    padding: .06  

    

  
