controller_list:
  - name: arm_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
  - name: lookat_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - torso_lower_neck_tilt_joint
      - torso_pan_joint
      - torso_upper_neck_tilt_joint
      - head_axis_joint
      - head_lookat_joint
